###
# app configuration
# https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html
###

[app:main]
use = egg:webmin_openvpn

pyramid.reload_templates = true
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = id
pyramid.includes =
    pyramid_chameleon
    pyramid_tm

sqlalchemy.url = postgresql://user:pass@localhost/openvpn

auth.secret = openvpn_auth_secret_sugiana_2026
session.secret = openvpn_session_secret_sugiana_2026

openvpn.client_dir = /etc/openvpn/client
openvpn.build_cert_cmd = /usr/local/bin/build-client-cert

###
# wsgi server configuration
###

[server:main]
use = egg:waitress#main
listen = 0.0.0.0:6543

###
# logging configuration
# https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
###

[loggers]
keys = root, webmin_openvpn, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_webmin_openvpn]
level = DEBUG
handlers =
qualname = webmin_openvpn

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s] %(message)s
